services:
  backend:
    build: .
    container_name: yuri-backend
    restart: always
    ports:
      - "3002:3002"
    environment:
      JWT_SECRET: "sua_chave_secreta"
      ADMIN_USER: "yuri"
      ADMIN_PASS: "yuribarber01"
      DATABASE_URL: "sqlite:///app/database.sqlite"
    volumes:
      - ./database.sqlite:/app/database.sqlite
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.srmendes.rule=Host(`api.unvgroup.tech`)"
      - "traefik.http.routers.srmendes.entrypoints=websecure"
      - "traefik.http.routers.srmendes.tls.certresolver=myresolver"

